spring.application.name=event-notificator
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5435/postgres
spring.datasource.password=pass
spring.datasource.username=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret-key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
jwt.lifetime=86400000
notification.clearing=0 */10 * * * *
topic.name=event-topic


