spring.application.name=event-manager
spring.datasource.url=jdbc:postgresql://localhost:5434/postgres
spring.datasource.password=pass
spring.datasource.username=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.url=/event-manager-openapi.yaml
jwt.secret-key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
jwt.lifetime=86400000
pass.admin=admin
pass.user=user
event.status.cron=10 * * * * *
topic.name=event-topic
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.UUIDSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer